### ISSUE TITLE
version 1.17 causes failure in newrelic_alert_policy_channel plan and creation

### ISSUE THREAD

**Issue by jpd4dazn** [terraform-providers/terraform-provider-newrelic#545] opened 2020-05-04 13:14 UTC
### Terraform Version
0.12.24

### Affected Resource(s)
- newrelic_alert_policy_channel

### Terraform Configuration Files
```hcl
resource "newrelic_alert_policy" "pagerduty" {
  name = "PagerDuty Alert Policy"
}

resource "newrelic_alert_policy_channel" "pagerduty" {
  count      = var.pagerduty_enabled ? 1 : 0
  policy_id  = newrelic_alert_policy.pagerduty.id
  channel_id = newrelic_alert_channel.alert_channel[0].id
}
```

### Expected Behavior
```
newrelic_alert_policy_channel.pagerduty[0]: Creating...
newrelic_alert_policy_channel.pagerduty[0]: Creation complete after 3s [id=
```

### Actual Behavior
```
newrelic_alert_policy_channel.pagerduty[0]: Creating...

Error: resource not found

  on policy.tf line 89, in resource "newrelic_alert_policy_channel" "pagerduty":
  89: resource "newrelic_alert_policy_channel" "pagerduty" {
```

or

```
newrelic_alert_policy_channel.pagerduty[0]: Refreshing state... [id=

Error: resource not found
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. have a tf with newrelic_alert_policy_channel to map policy to an alert channel applied with 1.16
2. `terraform plan` same config with 1.17

**Comment by MAN98** [comment] 2020-05-04 16:24
workaround is to pin the version of the terraform provider for new relic to 1.16.0

**Comment by jpd4dazn** [comment] 2020-05-04 16:30
done that

**Comment by jthurman42** [comment] 2020-05-04 21:57
Likely duplicate of #544

**Closed** 2020-05-05 14:49 UTC
Labels: duplicate
