### ISSUE TITLE
Provide (or release?) a way to set apdex_t for an existing new relic application

### ISSUE THREAD

**Issue by ryangardner** [terraform-providers/terraform-provider-newrelic#538] opened 2020-05-01 15:18 UTC
I was about to pull down this provider and start fumbling my way through trying to implement this myself, when I came across: 

https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_application.go

Which looks like it has the ability to do what I was needing. Is there a rough idea when the next release might go out that will include this feature? (If you accept bribes, what's your preferred way to be bribed?)

**Comment by jthurman42** [comment] 2020-05-01 17:55
There is a bit of work to get this into the provider, but there is an API endpoint to do so.  We're currently prepping to start a 2.x release cycle with the change required to enable this ability.

The specific endpoint in question is: https://api.newrelic.com/graphiql

with the following graphql query:

```
mutation {
  apmApplicationEntityChangeSettings(guid: "<MY APPLICATION ENTITY GUID>", settings: {apdexTarget: 0.5}) {
    entity {
      guid
      name
      settings {
        apdexTarget
      }
    }
  }
}
```

**Comment by ryangardner** [comment] 2020-05-01 18:45
Great, thanks for the reply!

We did see that graphql endpoint - (that currently only lets you set apdexTarget - but maybe someday will let you set other settings)

Is the current master branch getting ready for the 2.x release? We did build the current master version and what's inside there that lets you set the appdex and a couple other settings does seem to work (at least to set apdex): https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_application.go#L22-L36

(and one piece of feedback on that specific resource, since it hasn't been released yet...  you might want to consider naming it `applicationSettings` or something since the version there almost makes it seem like it will _create_ a new `application` in new relic rather than just _modify an existing one_ )

**Comment by jthurman42** [comment] 2020-05-01 19:45
Looks like this was merged into master just after the split, but appears to be backwards compatible.  @zlesnr any reason not to port the application resource to v1.x?

Good point on the naming, as this won't create an application.  We overrode the 'create' function to act as an import.  Read/Update/Delete should all function (note the API requires apps to stop reporting for 12 hours before a delete can occur, so this is also slightly unexpected behavior)

**Comment by zlesnr** [comment] 2020-05-01 20:26
Not that I see @jthurman42.  Looks like its all REST there.

**Comment by ctrombley** [comment] 2020-05-15 22:43
@ryangardner Support for this has been added in [v1.18.0 of the provider](https://github.com/terraform-providers/terraform-provider-newrelic/releases/tag/v1.18.0) via the [`newrelic_application_settings`](https://www.terraform.io/docs/providers/newrelic/r/application_settings.html) resource.  Give it a try and let us know if you have any issues.

**Closed by ctrombley** 2020-05-15 22:43 UTC
Labels: dependencies, enhancement, size/S
