### ISSUE TITLE
Terraform Import not resolving SSM Data Source

### ISSUE THREAD

**Issue by brapponotti** [terraform-providers/terraform-provider-newrelic#568] opened 2020-05-12 17:04 UTC
Hi there,

### Terraform Version
Terraform v0.12.17
+ provider.aws v2.61.0
+ provider.newrelic v1.17.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_ssm_parameter data source
- newrelic provider

I have tried to run terraform import on the following resources:
- newrelic_synthetics_monitor
- newrelic_alert_policy_channel
- newrelic_synthetics_alert_condition

All received the following error:
<img width="785" alt="Screen Shot 2020-05-12 at 9 30 49 AM" src="https://user-images.githubusercontent.com/58448666/81722116-c8b98380-9435-11ea-9274-5d9753fd5952.png">

### Terraform Configuration Files
```
data "aws_ssm_parameter" "new_relic_api_key" {
  name = var.new_relic_api_key_parameter
}

provider "newrelic" {
  api_key = data.aws_ssm_parameter.new_relic_api_key.value
  version = "1.17.0"
}

provider "aws" {
  region = var.region
}
```

### Expected Behavior
The resource should be imported as expected, with no issue related to the key specified. I have done a terraform plan which works with the new relic api key data source. The only time that I don't receive the config key error is if I hard code the key value into the api_key field.

### Actual Behavior
Import fails to recognize a key being present and throws:
Error: error initializing newrelic-client-go: use of ConfigPersonalAPIKey and/or ConfigAdminAPIKey is required

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a parameter in AWS Parameter Store that contains the correct API key value.
2. Create an aws_ssm_parameter data source that specifies this key name. 
3. Create a newrelic provider and aws provider, and set the version of newrelic provider to 1.17.
4. Set the api_key value of the newrelic provider to reference the value of ssm_parameter data source.

**Comment by ctrombley** [comment] 2020-05-13 19:07
Hey @brapponotti, I've reproduced your issue locally.  This does seem to be a problem specifically with the `import` command, as `plan` and `apply` both work as expected with this setup.  I've reached out to some Hashicorp engineers to see if they have a better idea about what's going on.  My feeling is that this is a Terraform core issue rather than a New Relic provider issue, but I will post here with more information when I get it.  Thanks for your patience.

**Comment by ctrombley** [comment] 2020-05-13 19:30
Looks like it's probably related to [this long-standing issue](https://github.com/hashicorp/terraform/issues/13018).

There are a few workarounds mentioned in that issue that may work for you.  If none of them work, you may need to eliminate the dynamic provider configuration while importing your existing resources, and then re-enable once you're finished.

**Comment by brapponotti** [comment] 2020-05-18 16:32
@ctrombley Fair enough, I can easily get around it by hardcoding the key in and running import as well. Or setting the key in a vars file so it's not hardcoded in the provider.tf file that I'd commit to source control.

**Comment by sanderblue** [comment] 2020-05-22 21:23
Closing since this seems to be an upstream issue with Terraform and a current workaround exists. If you feel we should reopen, please let us know. Thanks!

**Closed by sanderblue** 2020-05-22 21:23 UTC
Labels: bug, upstream-terraform
