### ISSUE TITLE
Issue using import with newrelic provider

### ISSUE THREAD

**Issue by ghstwhl** [terraform-providers/terraform-provider-newrelic#39] opened 2018-08-24 03:08 UTC
### Terraform Version
$ terraform --version
Terraform v0.11.8
+ provider.newrelic v1.0.1

### Affected Resource(s)
I'm sorry, I don't know how to answer this.

### Terraform Configuration Files
```provider "newrelic" {}

resource "newrelic_alert_policy" "foo" {
  name = "foo"
}

resource "newrelic_infra_alert_condition" "foo" {
  policy_id = "${newrelic_alert_policy.foo.id}"

  name       = "High disk usage"
  type       = "infra_metric"
  event      = "StorageSample"
  select     = "diskUsedPercent"
  comparison = "above"
  where      = "(`hostname` LIKE '%frontend%')"

  critical {
    duration      = 25
    value         = 90
    time_function = "all"
  }
}
```

### Debug Output
https://gist.github.com/ghstwhl/63354ee5834c0419efe972088328d394

### Expected Behavior
The import command should have linked the existing NewRelic alert condition with the sample one in my config, and I could have then used plan to identify the changes necessary to match the existing check in the tf config.

### Actual Behavior
The output first says the import completed, and it then says there was an error in parsing.

### Steps to Reproduce
1. copy the sample policy and check from https://www.terraform.io/docs/providers/newrelic/r/infra_alert_condition.html
2. use `terraform import` to link the policy to an existing New Relic Policy.
3. use `terraform import` to link the infra alert condition to an existing infrastructure alert.

### Important Factoids
The existing policy and infra checks I am trying to import are pretty generic:
```
Policy:
    {
      "updated_at": 1532403275005, 
      "incident_preference": "PER_CONDITION_AND_TARGET", 
      "created_at": 1531787485573, 
      "id": 283153, 
      "name": "Alerts that go ping"
    }, 
    

Alert Condition:
{
  "comparison": "above", 
  "select_value": "memoryUsedBytes/memoryTotalBytes*100", 
  "created_at_epoch_millis": 1531794178903, 
  "name": "High Memory Utilization", 
  "enabled": true, 
  "filter": {
    "and": [
      {
        "is": {
          "windowsPlatform": "Microsoft Windows Server 2012 R2 Standard"
        }
      }, 
      {
        "is": {
          "ec2Tag_owner": "email@domain.com"
        }
      }, 
      {
        "is": {
          "providerAccountName": "some-account"
        }
      }
    ]
  }, 
  "updated_at_epoch_millis": 1532403302548, 
  "event_type": "SystemSample", 
  "critical_threshold": {
    "duration_minutes": 15, 
    "value": 99.9, 
    "time_function": "all"
  }, 
  "type": "infra_metric", 
  "id": 5885249, 
  "policy_id": 283153
}, ```

**Comment by ss-remygreinhofer** [comment] 2018-11-19 18:09
```
$ terraform --version
Terraform v0.11.10
+ provider.newrelic v1.2.0
```

We are using the newest version of `terraform` and the newrelic provider, but we are still facing the problem described in this issue. 

Our policies and channels are correctly imported, but none of the conditions get linked to them. As a consequence, `tf plan` wants to recreate all of them.

**Comment by thejohnlin** [comment] 2019-03-14 01:45
@ghstwhl 
I ran into this issue recently and did some poking around.

I noticed you ran `terraform import` with what looks to be a policy ID.

If you take a look at the code beneath the covers, the provider is parsing the ID passed into `terraform import` and expecting two pieces: both the policy ID and the condition ID with a colon in the middle.

https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_alert_condition.go#L308

https://github.com/terraform-providers/terraform-provider-newrelic/blob/51875a56e41549e25dc74df484921412159bebf9/newrelic/helpers.go#L10

https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_alert_condition.go#L313-L314

If you import using `<policy_id>:<condition_id>`, you might see what I'm seeing now... which is a marshaling issue between float64 and string on the "threshold" field.

**Comment by ashwin1dd** [comment] 2019-05-16 22:28
Running into this as well. Has anyone been able to work around this?

**Comment by thejohnlin** [comment] 2019-05-24 17:20
> Running into this as well. Has anyone been able to work around this?
When I changed the type of the threshold field to be a string instead of float64, I was able to get it working.

**Comment by sanderblue** [comment] 2020-01-29 04:57
@ghstwhl Apologies for a delay in response. We've recently focused more resources on maintaining the provider and in doing so, we've updated the Terraform provider to our new client, [newrelic-client-go](https://github.com/newrelic/newrelic-client-go). In doing so, I have a hunch this might have been fixed as part of that update (or potentially as a result of other updates/fixes). I was unable to reproduce the primary reported problem with the current version of our provider, **v1.12.2**. I was also unable to reproduce the marshaling bug reported by @thejohnlin. Closing the issue since this looks to be resolved, but if anyone runs into any other issues please feel free to open new issue with your scenario.

**Closed by sanderblue** 2020-01-29 04:57 UTC
Labels: bug
