### ISSUE TITLE
Unable to specify payload for webhook in json

### ISSUE THREAD

**Issue by sharpjl** [terraform-providers/terraform-provider-newrelic#45] opened 2018-09-19 16:22 UTC
### Terraform Version
Terraform v0.10.8

### Affected Resource(s)

- newrelic_alert_channel with type of webhook

### Terraform Configuration Files
```hcl
resource "newrelic_alert_channel" "webhooktest" {
  name = "webhooktest"
  type = "webhook"

  configuration = {
    payload_type    = "application/json"
    auth_username   = "my_user",
    auth_password   = "my_password",
    base_url        = "thirdpartyurl",
    payload         = {"priority": 3, "status": 2, "description": "New Relic Notification"}
  }
}
```
### Expected Behavior
Create alert channel with payload in json format.

### Actual Behavior
Error: Error parsing main.tf: At 28:34: illegal char

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by bridgetlane** [comment] 2018-10-16 01:55
@sharpjl What line is line 28? Can you either direct me to the line or include your entire .tf file so that I can try to reproduce?

**Comment by ctrombley** [comment] 2019-11-06 22:34
Duplicate of #66

**Comment by ctrombley** [comment] 2019-11-06 22:34
Please continue future discussion in #66.

**Closed by ctrombley** 2019-11-06 22:34 UTC
