### ISSUE TITLE
Unable to set custom headers for webhook alert channel

### ISSUE THREAD

**Issue by mkubenka** [terraform-providers/terraform-provider-newrelic#18] opened 2017-10-04 08:40 UTC
### Terraform Version

Terraform v0.10.6

### Affected Resource(s)
- newrelic_alert_channel

### Terraform Configuration Files
```hcl
resource "newrelic_alert_channel" "api" {
  name = "API"
  type = "webhook"

  configuration = {
    base_url = "${var.url}"

    headers = {
      x-api-key = "${var.api_key}"
    }
  }
}
```

### Expected Behavior
Create alert channel with custom header `x-api-key`.

### Actual Behavior
```
1 error(s) occurred:

* newrelic_alert_channel.api: configuration (headers): '' expected type 'string', got unconvertible type '[]map[string]interface {}'
```

### Steps to Reproduce
1. `terraform apply`

**Comment by ctrombley** [comment] 2019-11-05 19:26
Duplicate of #66.

**Comment by ctrombley** [comment] 2019-11-05 19:27
Duplicate of #66

**Comment by ctrombley** [comment] 2019-11-06 22:35
Please continue future discussion in #66.

**Closed by ctrombley** 2019-11-06 22:35 UTC
Labels: bug
